
CREATE DATABASE `webapp`;

CREATE TABLE mst_system (
	multi		BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE mst_tenant (
	id			VARCHAR(20) NOT NULL,
	name		VARCHAR(50) NOT NULL DEFAULT '',
	note		VARCHAR(200) NOT NULL DEFAULT '',
	enable		BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (id)
);

CREATE TABLE mst_user (
	tenant_id	VARCHAR(20) NOT NULL,
	id			VARCHAR(50) NOT NULL,
	password	VARCHAR(50) NOT NULL,
	name		VARCHAR(50) NOT NULL DEFAULT '',
	role_id		VARCHAR(20) NOT NULL DEFAULT 1,
	expire		DATETIME NOT NULL DEFAULT '2099-12-31 23:59:59',
	visible		BOOLEAN NOT NULL DEFAULT TRUE,
	enable		BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY (tenant_id, id)
);

CREATE TABLE mst_role (
	id			VARCHAR(20) NOT NULL,
	name		VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

-- GRANT SELECT, UPDATE, INSERT, DELETE ON webapp.* TO 'webapp'@'localhost' IDENTIFIED BY 'webapp_pass';
